// <auto-generated />
using System;
using AdaByron.Infrastructure.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdaByron.Infrastructure.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260404113455_AddEdificioConfigPBI6")]
    partial class AddEdificioConfigPBI6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdaByron.Domain.Aggregates.PersonAggregate.Persona", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Email");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.ReservationAggregate.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EspacioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int>("NumeroAsistentes")
                        .HasColumnType("integer");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.SpaceAggregate.EdificioConfig", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<double>("PorcentajeOcupacion")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("edificio_config", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "AdaByron",
                            PorcentajeOcupacion = 100.0
                        });
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.SpaceAggregate.Espacio", b =>
                {
                    b.Property<string>("CodigoEspacio")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Aforo")
                        .HasColumnType("integer")
                        .HasColumnName("aforo");

                    b.Property<string>("CategoriaReserva")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EdificioConfigId")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Planta")
                        .HasColumnType("integer")
                        .HasColumnName("planta");

                    b.Property<string>("TipoFisico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("ubicacion");

                    b.HasKey("CodigoEspacio");

                    b.HasIndex("EdificioConfigId");

                    b.ToTable("espacios", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.PersonAggregate.Persona", b =>
                {
                    b.OwnsOne("AdaByron.Domain.Aggregates.PersonAggregate.Departamento", "Departamento", b1 =>
                        {
                            b1.Property<string>("PersonaEmail")
                                .HasColumnType("character varying(200)");

                            b1.Property<string>("Nombre")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Departamento");

                            b1.HasKey("PersonaEmail");

                            b1.ToTable("personas");

                            b1.WithOwner()
                                .HasForeignKey("PersonaEmail");
                        });

                    b.Navigation("Departamento")
                        .IsRequired();
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.ReservationAggregate.Reserva", b =>
                {
                    b.HasOne("AdaByron.Domain.Aggregates.SpaceAggregate.Espacio", null)
                        .WithMany("Reservas")
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdaByron.Domain.Aggregates.PersonAggregate.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdaByron.Domain.Aggregates.ReservationAggregate.FranjaHoraria", "Franja", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fin");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("ReservaId");

                            b1.ToTable("reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.Navigation("Franja")
                        .IsRequired();
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.SpaceAggregate.Espacio", b =>
                {
                    b.HasOne("AdaByron.Domain.Aggregates.SpaceAggregate.EdificioConfig", "EdificioConfig")
                        .WithMany()
                        .HasForeignKey("EdificioConfigId");

                    b.OwnsOne("AdaByron.Domain.Aggregates.PersonAggregate.Departamento", "Departamento", b1 =>
                        {
                            b1.Property<string>("EspacioCodigoEspacio")
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Nombre")
                                .HasMaxLength(150)
                                .HasColumnType("character varying(150)")
                                .HasColumnName("Departamento");

                            b1.HasKey("EspacioCodigoEspacio");

                            b1.ToTable("espacios");

                            b1.WithOwner()
                                .HasForeignKey("EspacioCodigoEspacio");
                        });

                    b.Navigation("Departamento")
                        .IsRequired();

                    b.Navigation("EdificioConfig");
                });

            modelBuilder.Entity("AdaByron.Domain.Aggregates.SpaceAggregate.Espacio", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
