// <auto-generated />
using System;
using AdaByron.Infrastructure.Persistence.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdaByron.Infrastructure.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    [Migration("20260316214921_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdaByron.Domain.Entities.Espacio", b =>
                {
                    b.Property<string>("CodigoEspacio")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Aforo")
                        .HasColumnType("integer")
                        .HasColumnName("aforo");

                    b.Property<string>("CategoriaReserva")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Planta")
                        .HasColumnType("integer")
                        .HasColumnName("planta");

                    b.Property<string>("TipoFisico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Point>("Ubicacion")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("ubicacion");

                    b.HasKey("CodigoEspacio");

                    b.ToTable("espacios", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Entities.Persona", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Departamento")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Email");

                    b.ToTable("personas", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EspacioId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PersonaId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EspacioId");

                    b.HasIndex("PersonaId");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("AdaByron.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("AdaByron.Domain.Entities.Espacio", null)
                        .WithMany()
                        .HasForeignKey("EspacioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdaByron.Domain.Entities.Persona", null)
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("AdaByron.Domain.ValueObjects.FranjaHoraria", "Franja", b1 =>
                        {
                            b1.Property<Guid>("ReservaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Fin")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("fin");

                            b1.Property<DateTime>("Inicio")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("inicio");

                            b1.HasKey("ReservaId");

                            b1.ToTable("reservas");

                            b1.WithOwner()
                                .HasForeignKey("ReservaId");
                        });

                    b.Navigation("Franja")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
